name: Build Image

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Container Image
        uses: docker/build-push-action@v4
        with:
          context: "./" # 현재 디렉터리를 컨텍스트로 설정
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: test:latest
