name: Build Image

on: [pull_request]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Backend Container Image
        uses: docker/build-push-action@v4
        with:
          context: ./KangChangsoo/backend/
          file: ./KangChangsoo/backend/Dockerfile
          platforms: linux/amd64
          push: false
          tags: test-backend:latest
  
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Frontend Container Image
        uses: docker/build-push-action@v4
        with:
          context: ./KangChangsoo/frontend/
          file: ./KangChangsoo/frontend/Dockerfile
          platforms: linux/amd64
          push: false
          tags: test-frontend:latest
